In [1]:
import numpy as np

In [3]:
a = np.array([[1,1],[1,-1]])
b = np.array([[1,1],[-1,1]])

In [4]:
print(a*b)

[[ 1  1]
 [-1 -1]]


In [5]:
print(np.where(a*b == -1))

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))


In [2]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = np.array([1,9,5,10])

In [3]:
b = np.array([1,2])

In [4]:
print(a*b)

[[ 1  4]
 [ 3  8]
 [ 5 12]
 [ 7 16]]


In [5]:
f = np.array([[1,2,3,4],[5,6,7,8]])
g = np.array([[9,10,11,12],[13,14,15,16]])

In [6]:
print(a)
print(b)

[2 4 6 8]
[ 1  9  5 10]


In [7]:
c = b - a
print(c)

[-1  5 -1  2]


In [8]:
d = np.where(c < 0)
print(d)

(array([0, 2], dtype=int64),)


In [9]:
print(a[d])

[2 6]


In [10]:
b[d] = a[d]

In [11]:
print(f)
print(g)
f[:,d] = g[:,d]
print(f)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9  2 11  4]
 [13  6 15  8]]


In [12]:
a = np.zeros((2, 10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
a[0] = 1

In [14]:
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [211]:
print(b)

[ 2  9  6 10]


In [210]:
print(a[range(0,4),index])

IndexError: too many indices for array

In [14]:
np.math.factorial(4)

24

In [116]:
a = []
for i in range(2**6):
    a.extend(format(i, 'b').zfill(11))

In [117]:
print(a)

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0',

In [119]:

a = np.reshape(a, (-1,11)).astype(int)

In [124]:
print(a)
a[:,5:] = np.where(a[:,5:] > 0, -1, 1)
print(a)

[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 1 0 1 1 0]
 [0 0 0 0 0 0 1 0 1 1 1]
 [0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 1]
 [0 0 0 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 1 1 0 1 1]
 [0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 1 1 1 0 1]
 [0 0 0 0 0 0 1 1 1 1 0]
 [0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 1 1]
 [0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 1 0 1]
 [0 0 0 0 0 1 0 0 1 1 0]
 [0 0 0 0 0 1 0 0 1 1 1]
