In [1]:
import numpy as np
from Source.GF32 import GFE
from Source.GF_function import GF_function
import keras
from keras.layers import Dense, Input, Add
from keras.models import Sequential, Model, load_model


Using TensorFlow backend.


In [2]:
GF = GF_function(32)
GF_2 = GF_function(64)

In [13]:
GF.GFE

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 0.],
       [0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 0., 0., 1.],
       [1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 0., 1., 0.],
       [0., 1., 1., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.]])

In [3]:
model = load_model('Model/p6_32_BCH_softmax.h5')
model_2 = load_model('Model/p6_64_BCH_softmax.h5')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



In [24]:
msg_size = 10**2

In [25]:
msg, codeword = GF.encoding(msg_size)
send_code = GF.send_code(codeword)

In [26]:
print(codeword)

[[11. 15. 14. ... 27. 10. 24.]
 [30.  9. 10. ... 19.  4.  0.]
 [ 0.  4. 25. ... 29. -1.  4.]
 ...
 [16. 27. 30. ... 16. 16. 24.]
 [ 6.  1. 12. ...  9. 19.  3.]
 [13.  6. 20. ... 17. 10.  3.]]


In [27]:
j = np.random.randint(11)
noise_code = GF.add_noise(j, send_code)
print(j)

9


In [28]:
result = model.predict(noise_code.reshape((-1,5)))

In [29]:
model_output = np.reshape(np.argmax(result, axis=1)-1,(msg_size,-1))

In [30]:
print(model_output)

[[11 15 14 ... 27 10 24]
 [30  9 10 ... 19  4  0]
 [ 0  4 25 ... 29 -1  4]
 ...
 [16 27 30 ... 16 16 24]
 [ 6  1 12 ...  9 19  3]
 [13  6 20 ... 17 10  3]]


In [31]:
error = np.where(codeword != model_output)[0].shape

In [32]:
print(error[0]/(31*msg_size))

0.0035483870967741938


In [46]:
msg_size = 10**2
msg, codeword = GF_2.encoding(msg_size)
send_code = GF_2.send_code(codeword)

In [52]:
j = np.random.randint(11)
j=10
noise_code = GF_2.add_noise(j, np.where(send_code > 0, -1, 1))
print(j)

10


In [53]:
result = model_2.predict(noise_code.reshape((-1,6)))

In [54]:
model_output = np.reshape(np.argmax(result, axis=1)-1,(msg_size,-1))

In [55]:
print(model_output)

[[-1 23 35 ... 10 55 11]
 [ 3 47 10 ... 35  5  4]
 [ 6 21 32 ... 62 33 57]
 ...
 [42 42 51 ... 27 17 34]
 [39 62 15 ... 19 11 36]
 [37 56 18 ...  8 10  8]]


In [56]:
error = np.where(codeword != model_output)[0].shape
print(error[0]/(63*msg_size))

0.12761904761904763
