In [1]:
import numpy as np

In [39]:
reqSNR = 10

In [3]:
a = np.random.randint(0,2, size=(10**6, 23))

In [4]:
print(a)

[[1 0 1 ... 1 0 1]
 [0 0 1 ... 0 1 0]
 [1 1 0 ... 0 1 0]
 ...
 [1 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 1]
 [0 0 1 ... 1 1 1]]


In [5]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i, j] == 0:
            a[i, j] = 1
        if a[i, j] == 1:
            a[i, j] = -1

In [6]:
print(abs(a))

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [7]:
print(abs(a)**2)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [8]:
print(np.sum(abs(a)**2, axis=1))

[23 23 23 ... 23 23 23]


In [40]:
sig_power = np.sum(abs(a)**2, axis=1)/a.shape[1]
print(sig_power)

[1. 1. 1. ... 1. 1. 1.]


In [41]:
sig_power = 10**(sig_power/10)
reqSNR = 10**(reqSNR/10)
print(sig_power, reqSNR)

[1.25892541 1.25892541 1.25892541 ... 1.25892541 1.25892541 1.25892541] 10.0


In [42]:
noise_power = sig_power / reqSNR

In [43]:
print(noise_power)
print(sig_power / noise_power)
noise_power = noise_power.reshape(10**6,1)
print(noise_power)



[0.12589254 0.12589254 0.12589254 ... 0.12589254 0.12589254 0.12589254]
[10. 10. 10. ... 10. 10. 10.]
[[0.12589254]
 [0.12589254]
 [0.12589254]
 ...
 [0.12589254]
 [0.12589254]
 [0.12589254]]


In [44]:
random = np.random.normal(size = a.shape)
print(random)
noise = np.sqrt(noise_power) * random

[[-0.00491642  0.20786408  1.38887043 ... -0.9191469   0.11906839
   0.58724344]
 [-0.51069396  1.42111092  0.40142208 ...  0.48684521  0.4800019
   0.18429962]
 [ 0.18269553  0.24015591 -1.09703315 ...  0.70642263 -0.49772417
   1.03996064]
 ...
 [-0.11130163  1.50169453  0.87497631 ... -2.74937557 -0.12922938
   0.16339815]
 [ 0.40901826  0.59135573 -0.32148638 ...  0.09664746 -0.9637245
   2.18341909]
 [-0.47941736  1.0172703  -1.95855865 ...  0.36555472 -1.3111636
   0.69379357]]


In [45]:
print(noise)

[[-0.00174441  0.07375296  0.49278983 ... -0.32612563  0.04224706
   0.20836183]
 [-0.18120105  0.50422918  0.14242993 ...  0.1727392   0.1703111
   0.06539197]
 [ 0.06482282  0.08521053 -0.38924205 ...  0.25064821 -0.1765992
   0.36899196]
 ...
 [-0.03949131  0.53282133  0.31045331 ... -0.97551527 -0.04585231
   0.05797585]
 [ 0.14512516  0.20982093 -0.11406767 ...  0.03429181 -0.34194236
   0.77470633]
 [-0.1701037   0.36094112 -0.69492283 ...  0.12970371 -0.4652184
   0.24616725]]


In [46]:
x = a  + noise

In [47]:
print(np.var(x))

0.12587991881948754
