In [1]:
import numpy as np
import keras

from keras.layers import Input, Lambda, Conv1D, Dense, Dropout, Flatten, MaxPooling1D, ZeroPadding1D
from keras.models import Model, Sequential
from keras.optimizers import Adam
from keras.callbacks import TensorBoard, ModelCheckpoint, ReduceLROnPlateau, EarlyStopping


Using TensorFlow backend.


In [2]:
input_path = 'input.txt'
classes_path = 'input.txt'

In [3]:
x = np.loadtxt(input_path)
y = np.loadtxt(classes_path)

In [4]:
print(x)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]]
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]]


In [5]:
x_train = x.reshape(x.shape[0], x.shape[1], 1)

In [6]:
num_classes = y.shape[0]

In [7]:
y_train = np.arange(num_classes)
y_train = keras.utils.to_categorical(y_train, num_classes)

In [8]:
input_shape= (23, 1)

In [9]:
batch_size = 200
epochs = 1

In [10]:
model = Sequential()
model.add(ZeroPadding1D(padding= 1, input_shape= input_shape))
model.add(Conv1D(23, kernel_size=3,
                 activation='relu',
                 strides = 1))
model.add(Conv1D(23, kernel_size=3,
                 activation='relu',
                 strides = 1))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(4096, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

In [11]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adam(),
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1)

Epoch 1/1


UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1d_1/convolution/Conv2D}} = Conv2D[T=DT_FLOAT, _class=["loc:@train...propFilter"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/conv1d_1/convolution/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1d_1/convolution/ExpandDims_1)]]

In [ ]:
score = model.evaluate(x_train, y_train, verbose=0)