In [1]:
import numpy as np
from Source import BEC

In [2]:
n_power=7
CodeRate=0.5
N_length=int(2**n_power)
msg_length=int(CodeRate*N_length)
frozen_length=N_length-msg_length
TotalNumMessage=4
codeNum = 10

Prob_start=0.15
Prob_delta=0.05
BEC_count=8
BECs=np.arange(Prob_start,Prob_start+BEC_count*Prob_delta,Prob_delta)

In [3]:
G_All=BEC.AllGeneratorMatrixPolarCode(n_power) ###생성행렬생성

In [4]:
(Z_BEC,Z_decending_index_BEC)=BEC.BhanttacharyyaParameterBEC(N_length, n_power)

In [5]:
SelectedBitsPositions = Z_decending_index_BEC[frozen_length:]
SelectedBitsPositions.sort()

In [6]:
FrozenBitsPositions = Z_decending_index_BEC[:frozen_length]
FrozenBitsPositions.sort()

In [7]:
msg, codeword = BEC.Encoding(codeNum, N_length, n_power, msg_length, SelectedBitsPositions, G_All[n_power]) 

In [11]:
# ReceviedBEC = BEC.ReceviedCode(EraseProb, codeword) ####전송받은 코드
ReceivedBEC = BEC.ReceivedCode(0.15, codeNum, N_length, codeword)

In [12]:
print(ReceviedBEC)

[[ 0.  0.  0. ...  0.  0.  1.]
 [-1.  0. -1. ...  0.  0.  1.]
 [ 0.  0.  1. ...  0.  1.  1.]
 ...
 [ 1.  0.  0. ...  1. -1.  0.]
 [ 1.  1.  1. ...  1.  0.  0.]
 [ 1.  1.  1. ...  1.  1. -1.]]


In [10]:
LLR_BEC = BEC.LLR_Value_BEC(ReceviedBEC) #### 0 to 77 1 to -77 -1 to 0

In [11]:
EstimatedMessage = BEC.Decoding(codeNum, N_length, n_power, SelectedBitsPositions, FrozenBitsPositions, 
                                G_All, LLR_BEC)

In [12]:
BER = BEC.BERCalculation(EstimatedMessage, msg, codeNum, msg_length)

In [13]:
print(BER)

0.0


In [14]:
print(BECs)

[0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5 ]
