In [7]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
from Source import golay

In [8]:
G = golay.make_G()

In [22]:
codeword_size = 10

m = np.random.randint(2, size = (codeword_size, 12))
codeword = np.dot(m,G) % 2

odd = np.where(codeword.sum(axis=1) % 2 == 1)
even_check = np.zeros((codeword_size, 1), dtype='int')
even_check[odd] = 1
codeword = np.concatenate((even_check, codeword), axis=1)
print("codeword: ", codeword)

noise = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])
codeword = (codeword + noise) % 2

# add noise

estimated_code = golay.syndrome_decoding(codeword)

codeword:  [[1 1 0 1 0 0 0 0 1 0 1 0 1 1 0 1 1 1 0 1 0 1 0 0]
 [1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 0 1 1 1]
 [0 0 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 1 1 1 1]
 [0 1 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 1 1 0 1 1 0 1]
 [0 1 0 1 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 1 1 1]
 [0 1 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
 [1 0 1 0 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 1]
 [0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1]
 [1 0 0 1 1 1 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0 1 1 0]
 [1 1 1 0 1 0 1 0 1 0 0 1 0 1 1 1 1 1 0 0 1 1 1 1]]
code [1 1 0 1 0 0 0 0 1 0 1 0 1 1 0 1 1 1 0 1 1 0 1 1]
even_check 1
code_syndrome (1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0)
error_code [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
code [1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 0 0]
even_check 1
code_syndrome (1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0)
error_code [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
code [0 0 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0]
even_check 0
code_syndrome (1

In [23]:
print(codeword)

[[1 1 0 1 0 0 0 0 1 0 1 0 1 1 0 1 1 1 0 1 1 0 1 1]
 [1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 0 0]
 [0 0 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0]
 [0 1 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0]
 [0 1 0 1 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 0 0 0]
 [0 1 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1 0 1 0 1 1 1 0]
 [1 0 1 0 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 1 1 1 0]
 [0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 1 0]
 [1 0 0 1 1 1 0 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 0 1]
 [1 1 1 0 1 0 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 0 0 0]]


In [24]:
print(estimated_code)

[[ 1  1  1  0  0  0  0  1  0  1  1  1  1  1  1  1  1  0  1  1  0  1  1]
 [ 0  1  0  0  0  1  1  1  0  0  0  0  0  0  0  1  1  0  1  1  0  0  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  1  1  0  0  1  1  1  1  0  0  1  1  1  0  0  1  1  1  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  1  1  1  1  0  0  1  1  0  0  0  1  1  0  0  1  1  0  1  0  0  1]
 [ 1  0  0  1  0  1  0  1  0  0  0  0  1  0  1  1  1  0  0  0  0  0  0]]


In [25]:
print(m)
print(estimated_code[:,11:])

[[1 1 0 1 1 1 0 1 0 1 0 0]
 [0 0 1 0 1 1 0 1 0 1 1 1]
 [0 0 1 0 0 0 1 0 1 1 1 1]
 [1 0 0 0 0 1 1 0 1 1 0 1]
 [1 1 1 0 1 0 1 0 0 1 1 1]
 [0 0 1 1 1 0 1 0 0 0 0 1]
 [1 0 1 1 1 1 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 1 0 1]
 [0 1 0 0 0 1 1 0 0 1 1 0]
 [0 1 1 1 1 1 0 0 1 1 1 1]]
[[ 1  1  1  1  1  1  0  1  1  0  1  1]
 [ 0  0  0  0  1  1  0  1  1  0  0  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  0  0  1  1  1  0  0  1  1  1  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  1  1  0  0  1  1  0  1  0  0  1]
 [ 0  1  0  1  1  1  0  0  0  0  0  0]]


In [26]:
np.where((m == estimated_code[:,11:]) == False)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9],
       dtype=int64),
 array([ 2,  8,  9, 10, 11,  2,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
         0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
         5,  6,  7,  8,  9, 10, 11,  2,  8,  9, 10, 11,  0,  1,  2,  3,  4,
         5,  6,  7,  8,  9, 10, 11,  2,  8,  9, 10, 11,  2,  8,  9, 10, 11],
       dtype=int64))