In [1]:
import numpy as np

In [2]:
def _make_3bit_errors(veclen=23):
    """ return list of all bitvectors with <= 3 bits as 1's, rest 0's
    returns list of lists, each 24 bits long by default.
    not included:
    [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0]
    included:
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    """
    errorvecs = []
    # all zeros
    errorvecs.append([0] * veclen)
    # one 1
    for i in range(veclen):
        vec = [0] * veclen
        vec[i] = 1
        errorvecs.append(vec)

    # two 1s
    for i in range(veclen):
        for j in range(i + 1, veclen):
            vec = [0] * veclen
            vec[i] = 1
            vec[j] = 1
            errorvecs.append(vec)

    # three 1s
    for i in range(veclen):
        for j in range(i + 1, veclen):
            for k in range(j + 1, veclen):
                vec = [0] * veclen
                vec[i] = 1
                vec[j] = 1
                vec[k] = 1
                errorvecs.append(vec)
    return errorvecs

In [6]:
errvecs = np.array(_make_3bit_errors())

In [7]:
print(errvecs)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 1 1 1]]


In [11]:
print(errvecs.sum(axis=1))

[0 1 1 ... 3 3 3]


In [8]:
P = np.array([
    [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1],
    [1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
    [1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1],
    [1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0],
    [0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0],
    [0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1],
    [1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
    [0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0],
    [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
    [1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0],
    [0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
], dtype='int')
H = np.concatenate((np.eye(11, dtype="int"), P.T), axis=1)

In [23]:
syn = np.dot(errvecs, H.T)%2

In [14]:
print(syn.shape)

(2048, 11)


In [15]:
syn[1] == syn[2]

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [12]:
print(syn.sum(axis=1))

[0 1 1 ... 4 9 5]


In [19]:
np.savetxt('syndrome.csv', syn, delimiter=',')

In [169]:
a = np.random.randint(2, size=(2,23))

In [177]:
b =  list(tuple(np.dot(a, H.T) % 2))

In [178]:
print(b)

[array([1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0], dtype=int32), array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0], dtype=int32)]


In [30]:
import pickle

In [31]:
with open('syndrome.pickle', 'rb') as syn:
        syndrome = pickle.load(syn)

In [172]:
key = list(syndrome.keys())
value = list(syndrome.values())

In [173]:
key == b

False

In [174]:
print(len(key))

2048


In [147]:
key[0]

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)